### ISSUE TITLE
Java 9 / module support

### ISSUE THREAD

**Issue by emilssolmanis** [googleapis/java-secretmanager#129]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
As it stands, the client doesn't work with Java 9+ modules due to split packages. The data objects are genned from proto, put in a separate jar, and get the automodule name of `proto.google.cloud.secretmanager.v1`. The actual logic / clients are in another jar, and get the automodule name `google.cloud.secretmanager`. Both of these modules declare the same packages, `com.google.cloud.secretmanager.v1` and `v1beta1`.

Both the API objects and the clients would normally be consumed from the same module / class, so this causes compilation failures when using a `module-info.java` to declare the dependencies.

**Describe the solution you'd like**
Preferably, Java module support. Though this is likely backwards incompatible.
Making package names unique to artifacts / jars would be acceptable and make this usable with Java modules, i.e., make `proto-google-cloud-secretmanager-v1-1.0.1.jar` export something like `com.google.cloud.secretmanager.proto.v1`, and `google-cloud-secretmanager-1.0.1.jar` export `com.google.cloud.secretmanager.v1`. This would still _technically_ be backwards incompatible in that clients would need to tweak their imports, but it's a minor change and would make it usable with Java 9 modules.

**Describe alternatives you've considered**
I've considered not using modules, which I'll have to resort to, short of repackaging Google jars, which feels worse.

**Additional context**
None, really.

**Comment by chingor13** [comment]
Thanks for filing this. This is a [known issue](https://github.com/googleapis/google-cloud-java/issues/5760) that we don't have a solution for at this time. 

Our options at the moment are:
1. forcing an uber jar - this would prevent users from depending on just the proto classes and would need to take the entire cloud library as a dependency.
2. changing the Java package names so multiple packages do not provide the same Java package. This is problematic because Java package names are explicitly declared inside of the .proto files and can cause tooling errors as the proto messages/services would not match the generated output.

In either case, grpc also has the same issue (on a smaller scale) and we would be blocked on that one anyways.
